In [1]:
import pandas as pd
import numpy as np

In [17]:
entrada = pd.read_csv("in.csv")
salida = pd.read_csv("out.csv")

In [19]:
# ver la cantidad de puntos detectados para un frame en el df de entrada y salida

for i in range (salida['frame'].max()+1):

    if len(salida.loc[salida['frame'] == i]) != 0: #que exista el frame
        
        # armo dataframes de entrada y salida que contienen solo un frame
        new_in = entrada.loc[entrada['frame'] == i] 
        new_out = salida.loc[salida['frame'] == i]
        
        if new_in.shape[0] > new_out.shape[0]:
            print(new_in.shape[0],new_out.shape[0])

36 35
41 36
37 36
38 36
38 36
40 37
39 38
34 33
35 33
35 34
37 35
37 36
40 36
37 36
37 36
37 36
37 35
38 36
38 36
38 36
37 36
39 38

In [5]:
#modificar columnas de el archivo de entrada para ponerle un nombre a la pirmera columna que es igual al index
entrada.columns = ['nro_index','y','x','frame','ctcf','mean_gray_value']

In [9]:
cost = np.zeros([salida.shape[0],entrada.shape[0]])
for it_out in range(salida.shape[0]):
    
    x_out, y_out = salida.loc[it_out, "x"], salida.loc[it_out, "y"]
    
    for it_in in range(entrada.shape[0]):

        x_in, y_in = entrada.loc[it_in, "x"], entrada.loc[it_in, "y"]
        distance = np.sqrt((x_out-x_in)**2 + (y_out-y_in)**2)
        cost[it_out,it_in] = distance

In [11]:
from scipy.optimize import linear_sum_assignment
row_ind, col_ind = linear_sum_assignment(cost)
row_ind

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22], dtype=int64)

In [6]:
from scipy.optimize import linear_sum_assignment

prev_index=0
for i in range (salida['frame'].max()+1):

    if len(salida.loc[salida['frame'] == i]) != 0: #que exista el frame
        
        # armo dataframes de entrada y salida que contienen solo un frame
        new_in = entrada.loc[entrada['frame'] == i]
        new_in = new_in.reset_index() 
        new_out = salida.loc[salida['frame'] == i]
        
        # creo y relleno la matriz de costos
        cost = np.zeros([new_out.shape[0],new_in.shape[0]])

        k_out = 0 # preciso un iterador que cuente desde 0
        for it_out, row in new_out.iterrows():    
            x_out, y_out = new_out.loc[it_out, "x"], new_out.loc[it_out, "y"]
    
            for it_in , row in new_in.iterrows():
                x_in, y_in = new_in.loc[it_in, "x"], new_in.loc[it_in, "y"]
                distance = np.sqrt((x_out-x_in)**2 + (y_out-y_in)**2)
                cost[k_out,it_in] = distance
            k_out = k_out+1
          
        row_ind, col_ind = linear_sum_assignment(cost)
          
        if frame==4:
            #print(new_in)
            print(row_ind)
            print(col_ind)
            print(new_in.shape[0],new_out.shape[0])
        for it in range(new_out.shape[0]):
            if frame==4:
                print(col_ind[it])
            mean_gray_value = new_in.loc[col_ind[it], 'mean_gray_value']
            salida.loc[prev_index+it,'fluorescence'] = mean_gray_value
        
        prev_index = prev_index+it+1

0
1
2

In [7]:
salida

    id           x           y  fluorescence  frame
0    4  184.474576   34.593220     76.389831      2
1    5  235.000000   47.150000     52.600000      2
2    8  233.935484   57.569892    115.967742      2
3    2   28.404762    9.440476    102.916667      2
4    3   99.458537   35.102439    140.756098      2
5    6   63.153846   48.326923     98.807692      2
6   10   46.476190   74.285714     90.777778      2
7    7  495.119048   56.595238    132.571429      2
8    9  337.718519   63.370370     68.555556      2
9   11  421.737778  107.324444    166.582222      2
10  12  102.658120  122.700855    119.222222      2
11  13  483.669811  147.509434    106.896226      2
12  14  352.201342  166.590604    129.355705      2
13  15  249.069767  173.779070    142.976744      2
14  16  242.762887  173.567010     54.090909      2
15  17  138.600000  182.300000     53.850000      2
16  18  145.676471  191.882353     65.058824      2
17  19  303.772727  197.659091     76.227273      2
18  20    4.169492  201.610169     73.101695      2
19  21  434.987500  208.937500    115.275000      2
20  23  418.148936  229.404255    136.117021      2
21  22  259.386243  232.873016    138.555556      2
22  24   48.144737  229.684211    139.684211      2
23  25   31.544554  247.257426    124.148515      2
24  26  390.907692  334.082051    125.846154      2
25  27  373.659794  394.010309    125.268041      2
26  31  398.128571  413.914286    120.485714      2
27  32  429.510753  416.024194    154.653226      2
28  28  175.875000  395.750000    117.045455      2
29  29  202.785714  411.904762    144.535714      2
30  30   45.000000  416.445122    118.097561      2
31  34  107.467105  421.651316    113.039474      2
32  35   82.653465  443.207921    107.752475      2
33  33  322.050000  412.428571    152.292857      2
34  36  397.543902  476.131707    154.219512      2

In [8]:
entrada

    nro_index           y           x  frame          ctcf  mean_gray_value
0          70   12.329114  248.202532    2.0  26525.506268       113.873418
1          71    9.440476   28.404762    2.0   8481.078171       102.916667
2          72   35.102439   99.458537    2.0  28454.952679       140.756098
3          73   34.593220  184.474576    2.0   4391.864429        76.389831
4          74   48.326923   63.153846    2.0  10073.049164        98.807692
5          75   47.150000  235.000000    2.0   1012.970993        52.600000
6          76   56.595238  495.119048    2.0  10972.078171       132.571429
7          77   57.569892  233.935484    2.0  10603.515118       115.967742
8          78   63.370370  337.718519    2.0   8991.554203        68.555556
9          79   74.285714   46.476190    2.0   5596.058628        90.777778
10         80   75.636364  335.909091    2.0    573.534046        54.090909
11         81  107.324444  421.737778    2.0  37041.923672       166.582222
12         82  122.700855  102.658120    2.0  13720.680309       119.222222
13         83  147.509434  483.669811    2.0  11124.146263       106.896226
14         84  166.590604  352.201342    2.0  18983.233898       129.355705
15         85  173.779070  249.069767    2.0  12128.175270       142.976744
16         86  182.300000  138.600000    2.0   1037.970993        53.850000
17         87  191.882353  145.676471    2.0   2145.650688        65.058824
18         88  197.659091  303.772727    2.0   3268.136185        76.227273
19         89  201.610169    4.169492    2.0   4197.864429        73.101695
20         90  208.937500  434.987500    2.0   9065.883972       115.275000
21         91  232.873016  259.386243    2.0  25818.175884       138.555556
22         92  229.404255  418.148936    2.0  12611.563667       136.117021
23         93  229.684211   48.144737    2.0  10467.689774       139.684211
24         94  247.257426   31.544554    2.0  12341.903515       124.148515
25         95  334.082051  390.907692    2.0  24159.467182       125.846154
26         96  394.010309  373.659794    2.0  11961.709316       125.268041
27         97  395.750000  175.875000    2.0  10128.272369       117.045455
28         98  416.445122   45.000000    2.0  19047.962143       118.097561
29         99  416.024194  429.510753    2.0  56805.060471       154.653226
30        100  412.428571  322.050000    2.0  21047.796951       152.292857
31        101  411.904762  202.785714    2.0  11977.078171       144.535714
32        102  413.914286  398.128571    2.0   8297.398476       120.485714
33        103  421.651316  107.467105    2.0  16885.379547       113.039474
34        104  443.207921   82.653465    2.0  10685.903515       107.752475
35        105  476.131707  397.543902    2.0  62429.905357       154.219512